windows_task:
  name: WSL Output
  script: 
    - ps: |
        $ProgressPreference = 'SilentlyContinue'
        wsl --status | Write-Output
        Write-Output Done
  compute_engine_instance:
    image_project: jtgreene-podman # GCP project
    image: family/windows-podman # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 200 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.

windows_task:
  pre_script:
    - ps: | 
        $ProgressPreference = 'SilentlyContinue'
        wsl --status
        wsl -l
        choco feature enable -n allowGlobalConfirmation
        choco install golang 
  build_script:
    - refreshenv
    - ps: | 
        try {
          mkdir bin\windows
          $env:CGO_ENABLED = 0
          go build `
            -mod=vendor  `
            -ldflags '-X github.com/containers/podman/v3/libpod/define.gitCommit=5852cee4c517f303ed5122ea28cd9b1dad6e04c2 -X github.com/containers/podman/v3/libpod/define.buildInfo=1639692734 -X github.com/containers/podman/v3/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v3/libpod/config._etcDir=/usr/local/etc ' `
            -tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" `
            -o bin\windows\podman.exe .\cmd\podman 
          Write-Output 'Made it here.'
          dir bin\windows 
          bin\windows\podman.exe system connection list 
        } catch {$_; exit 1}
  compute_engine_instance:
    image_project: jtgreene-podman # GCP project
    image: family/windows-podman # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 200 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to falsewindows_task:
  name: WSL Output
  script: 
    - ps: |
        $ProgressPreference = 'SilentlyContinue'
        wsl --status | Write-Output
        Write-Output Done
  compute_engine_instance:
    image_project: jtgreene-podman # GCP project
    image: family/windows-podman # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 200 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.

windows_task:
  pre_script:
    - ps: | 
        $ProgressPreference = 'SilentlyContinue'
        wsl --status
        wsl -l
        choco feature enable -n allowGlobalConfirmation
        choco install golang 
  build_script:
    - refreshenv
    - ps: | 
        try {
          mkdir bin\windows
          $env:CGO_ENABLED = 0
          go build `
            -mod=vendor  `
            -ldflags '-X github.com/containers/podman/v3/libpod/define.gitCommit=5852cee4c517f303ed5122ea28cd9b1dad6e04c2 -X github.com/containers/podman/v3/libpod/define.buildInfo=1639692734 -X github.com/containers/podman/v3/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v3/libpod/config._etcDir=/usr/local/etc ' `
            -tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" `
            -o bin\windows\podman.exe .\cmd\podman 
          Write-Output 'Made it here.'
          dir bin\windows 
          bin\windows\podman.exe system connection list 
        } catch {$_; exit 1}
  compute_engine_instance:
    image_project: jtgreene-podman # GCP project
    image: family/windows-podman # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 200 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
