
windows_task:
  script:
    - ps: | 
        wsl --status 
        choco feature enable -n allowGlobalConfirmation
        choco install make
        choco install golang
        make podman-remote-windows
  compute_engine_instance:
    image_project: jtgreene-podman # GCP project
    image: family/windows-podman # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 200 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
