win_installer_task:
    name: "Verify Win Installer Build"
#    depends_on:
    windows_container:
        image: cirrusci/windowsservercore:2019
    env:
        CIRRUS_SHELL: powershell
        CIRRUS_CLONE_DEPTH: 1
        WIN_INSTALLER_SRC_RELEASE: 4.2.0
#        CIRRUS_WORKING_DIR: "${CIRRUS_DEFAULT_WORK}"
    install_script: | 
        Set-Service -Name wuauserv -StartupType "Manual"
        choco install -y wixtoolset mingw golang dotnet-sdk archiver curl
        Exit $LASTEXITCODE
    main_script: | 
        refreshenv
        Set-Location contrib\win-installer
        .\build.ps1 $ENV:WIN_INSTALLER_SRC_RELEASE
