
windows_task:
  script:
    - ps: Get-Location  
  compute_engine_instance:
    image_project: windows-cloud # GCP project
    image: windows-2019 # family or a full image name.
    platform: windows
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    disk: 100 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
  
 
