win_installer_task:
    name: "Verify Win Installer Build"
#    depends_on:
    windows_container:
        image: cirrusci/windowsservercore:2019
    env:
        CIRRUS_SHELL: powershell
        CIRRUS_CLONE_DEPTH: 1
        WIN_INSTALLER_SRC_RELEASE: 4.2.0
#        CIRRUS_WORKING_DIR: "${CIRRUS_DEFAULT_WORK}"
    install_script: | 
        # Update service is required for dotnet 3.5 (dep of wix)
        Set-Service -Name wuauserv -StartupType "Manual"
        choco install -y wixtoolset mingw golang archiver curl
        if ($LASTEXITCODE -ne 0) {
            Exit 1
        }
    main_script: | 
        Set-Location contrib\win-installer
        .\build.ps1 $ENV:WIN_INSTALLER_SRC_RELEASE
        if ($LASTEXITCODE -ne 0) {
            Exit $LASTEXITCODE
        }
        $ret = Start-Process -Wait -PassThru .\podman-4.2.0-dev-setup.exe -ArgumentList "/install /quiet WSLCheckbox=0 AllowOldWin=1 /log inst.log"
        if ($ret.ExitCode -ne 0) {
            Write-Host "Install failed, dumping log"
            Get-Content inst.log
            Exit $ret.ExitCode
        }
        $ret = Test-Path -Path "C:\Program Files\RedHat\Podman\podman.exe"
        if (! $ret) {
            Write-Host "Expected podman.exe, not present after install"
            Exit 1
        }
        Write-Host "Installer verification successful!"
